apiVersion: v1
kind: Pod
metadata:
  name: backend-build
spec:
  containers:
    - name: gcloud-docker
      image: 'google/cloud-sdk'  # gcloud SDK base image
      command: [ "sleep" ]
      args: [ "infinity" ]
      env:
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"  # Docker socket
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                apt-get update && \
                apt-get install -y docker.io kubectl

    - name: maven-container
      image: 'maven:3.8.6-eclipse-temurin-17'  # Maven base image
      command: [ "sleep" ]
      args: [ "infinity" ]
    
    containers:
    - name: sonarqube-scanner
      image: 'sonarsource/sonar-scanner-cli'
      command: [ "sleep" ]
      args: [ "infinity" ]
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                apt-get update && \
                apt-get install -y maven
      resources:
        requests:
          memory: "2Gi"  # Adjust based on your needs
          cpu: "1"
        limits:
          memory: "4Gi"  # Adjust based on your needs
          cpu: "2"

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
