apiVersion: v1
kind: Pod
metadata:
  name: backend-build
spec:
  containers:
    - name: gcloud-docker
      image: 'google/cloud-sdk'
      command: ["sleep"]
      args: ["infinity"]
      env:
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                apt-get update && \
                apt-get install -y docker.io kubectl && \
                echo "Docker and kubectl installed successfully" || \
                echo "Error installing Docker and kubectl" > /tmp/post_start_error.log

    - name: maven-junit
      image: 'maven:3.8.3-openjdk-17'
      command: ["sleep"]
      args: ["infinity"]
      workingDir: /workspace
      volumeMounts:
        - name: source-code
          mountPath: /workspace
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                apt-get update && \
                apt-get install -y jq curl maven && \
                echo "Maven, jq, and curl installed successfully" || \
                echo "Error installing Maven, jq, and curl" > /tmp/post_start_error.log

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: source-code
      emptyDir: {}
